# -*- coding: utf-8 -*-

"""
wordsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CustomHeaderAuthentication:

    def __init__(self, x_rapid_api_key):
        self._x_rapid_api_key = x_rapid_api_key

    def validate_arguments(self):
        if self._x_rapid_api_key:
            return True
        return False

    def apply(self, http_request):
        """ Add custom authentication to the request.

        Args:
            http_request (HttpRequest): The HttpRequest object to which
                authentication will be added.

        """
        http_request.add_header("X-RapidAPI-Key", self._x_rapid_api_key)

    def error_message(self):
        """Display error message on occurrence of authentication faliure
        in CustomHeaderAuthentication

        """
        return "CustomHeaderAuthentication: _x_rapid_api_key is undefined."
