name: Publish Package

on:
  workflow_dispatch

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*
#       - name: Publish distribution to PyPI
#         uses: pypa/gh-action-pypi-publish@v1.5.1
#         with:
#           password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish a Python distribution to PyPI
        uses: ortega2247/pypi-upload-action@master
        with:
          user: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}
